project: 
  type: website
  
website: 
  reader-mode: true
  page-navigation: true
  title: "DfE Statistics Hub" 
  site-url: "https://dfe-analytical-services.github.io/stats-production-guidance-quarto/" 
  repo-url: https://github.com/dfe-analytical-services/stats-production-guidance-quarto 
  repo-actions: [issue]
  
  page-footer:
    right: "This page is maintained by the Statistics Developlment Team"
    left: "Department for Education, 2023"
  
  search:
    location: sidebar
    type: overlay
  
  sidebar:
    logo: "images/duck_guidance.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://explore-education-statistics.service.gov.uk/
        text: "Explore Education Statistics"
      - icon: github
        href: https://github.com/dfe-analytical-services
        text: "DfE Analytical Services"

    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: learning-development/learning-development.qmd
        contents:
          - learning-development/sql.qmd
          - learning-development/r.qmd
          - learning-development/git.qmd
      - section: "Creating statistics"
        contents: 
          - creating-statistics/rap.qmd
          - creating-statistics/rap-managers.qmd
          - creating-statistics/ud.qmd
          - creating-statistics/cd.qmd
      - section: "Publishing statistics"
        contents: 
          - publishing-statistics/pub.qmd
          - publishing-statistics/ees.qmd
          - publishing-statistics/accessibilit-ees.qmd
          - publishing-statistics/examples.qmd
          - publishing-statistics/dashboards.qmd
          - publishing-statistics/embedded-charts.qmd
      - section: "Understanding users"
        contents: 
          - understanding-users/user-eng.qmd
          - understanding-users/user-analytics.qmd

format:
  html:
    theme:
      light: flatly
      dark: slate
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
