# .github/workflows/render-and-publish.yaml https://github.com/marketplace/actions/quarto-render
name: Render and deploy Quarto files
on:
  push:
    main
    
jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: "Install Quarto and render"
        uses: pommevilla/quarto-render@main

      - name: Render Quarto Project
        run: |
          quarto render --output-dir docs/
      - name: Commit files  # transfer the new html files back into the repository
        run: |
          git config --local user.name  ${{ github.actor }}
          git add .
          git commit -m "Updating the repository GitHub html pages in the docs folder"
      - name: Push changes  
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          