name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout️
        uses: actions/checkout@v3 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Quarto Project
        run: |
          quarto render --output-dir docs/
      - name: Commit files  # transfer the new html files back into the repository
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./docs
          git commit -m "Updating the repository GitHub html pages in the docs folder"
      - name: Push changes  
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ gh-pages }}
          force: true
